#!/bin/bash -l
#echo "z1_making_slices_run_rings_code.bsh"
#./z1_making_slices_run_rings_code.bsh

echo "z2_extract_rings_info_Rc_PercentOfRings_from_slices_and_average_them.bsh"
./z2_extract_rings_info_Rc_PercentOfRings_from_slices_and_average_them.bsh


echo "z3_extract_bond_length_information_of_each_IrreducibleRing_from_all_slices_and_avg_them.bsh"
./z3_extract_bond_length_information_of_each_IrreducibleRing_from_all_slices_and_avg_them.bsh

echo "z4_extract_bond_length_information_of_each_ReducibleRing_from_all_slices_and_avg_them.bsh"
./z4_extract_bond_length_information_of_each_ReducibleRing_from_all_slices_and_avg_them.bsh

echo "z5_extract_angle_information_of_each_IrreducibleRing_from_all_slices_and_avg_them.bsh"
./z5_extract_angle_information_of_each_IrreducibleRing_from_all_slices_and_avg_them.bsh

echo "z6_extract_angle_information_of_each_ReducibleRing_from_all_slices_and_avg_them.bsh"
./z6_extract_angle_information_of_each_ReducibleRing_from_all_slices_and_avg_them.bsh

echo "z7_extract_dihedral_angle_information_of_each_IrreducibleRing_from_all_slices_and_avg_them.bsh"
./z7_extract_dihedral_angle_information_of_each_IrreducibleRing_from_all_slices_and_avg_them.bsh

echo "z8_extract_dihedral_angle_information_of_each_ReducibleRing_from_all_slices_and_avg_them.bsh"
./z8_extract_dihedral_angle_information_of_each_ReducibleRing_from_all_slices_and_avg_them.bsh

